<?php

namespace App\Services;

use App\Models\AssessmentAttempt;
use App\Models\AudioFile;
use App\Models\Learner;
use App\Models\Report;
use App\Models\SchoolClass;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\File;
use PhpOffice\PhpSpreadsheet\Cell\DataType;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use RuntimeException;

class CrlaExcelExportService
{
    private const TEMPLATE_PATH = 'app/templates/crla/CRLA3_Grade1Scoresheet_v3_readirect.xlsx';

    private const FIRST_LEARNER_ROW = 11;

    private const MAX_LEARNER_ROWS = 100;

    public function refreshForAttempt(AssessmentAttempt $attempt): Report
    {
        $this->raiseMemoryLimit();

        $attempt->loadMissing(['learner.school', 'learner.schoolClass']);

        $templatePath = storage_path(self::TEMPLATE_PATH);

        if (! is_file($templatePath)) {
            throw new RuntimeException("CRLA Excel template was not found at {$templatePath}.");
        }

        $assessmentType = (string) $attempt->attempt_type;
        $learner = $attempt->learner;
        $class = $learner->schoolClass;
        $attempts = $this->attemptsForWorkbook($attempt);
        $relativePath = $this->relativeExportPath($assessmentType, $class, $learner);
        $absolutePath = storage_path('app/'.$relativePath);

        File::ensureDirectoryExists(dirname($absolutePath));

        $spreadsheet = IOFactory::load($templatePath);
        $this->writeWorkbook($spreadsheet, $attempts, $assessmentType, $class, $learner);

        $writer = new Xlsx($spreadsheet);
        $writer->setPreCalculateFormulas(false);
        $writer->save($absolutePath);

        $report = Report::updateOrCreate(
            [
                'learner_id' => $class ? null : $learner->id,
                'school_id' => $learner->school_id,
                'class_id' => $class?->id,
                'report_type' => $this->reportType($assessmentType),
            ],
            [
                'status' => 'generated',
                'file_path' => $relativePath,
                'payload' => [
                    'generated_at' => now()->toISOString(),
                    'assessment_type' => $assessmentType,
                    'class_id' => $class?->id,
                    'class_name' => $class?->name,
                    'school_id' => $learner->school_id,
                    'learner_ids' => $attempts->pluck('learner_id')->values()->all(),
                    'assessment_attempt_ids' => $attempts->pluck('id')->values()->all(),
                    'template_path' => self::TEMPLATE_PATH,
                ],
            ]
        );

        $spreadsheet->disconnectWorksheets();

        return $report;
    }

    private function writeWorkbook(Spreadsheet $spreadsheet, Collection $attempts, string $assessmentType, ?SchoolClass $class, Learner $fallbackLearner): void
    {
        $scoresheet = $spreadsheet->getSheetByName('G1 MT Reading Scoresheet');
        $classRecord = $spreadsheet->getSheetByName('Class Record');
        $classSummary = $spreadsheet->getSheetByName('Class Summary');

        if (! $scoresheet || ! $classRecord || ! $classSummary) {
            throw new RuntimeException('The CRLA template is missing one or more required sheets.');
        }

        $this->writeHeader($scoresheet, $assessmentType, $class, $fallbackLearner);
        $this->writeClassRecordHeader($classRecord, $class, $fallbackLearner);
        $this->writeClassSummaryHeader($classSummary, $class, $fallbackLearner);

        foreach ($attempts->take(self::MAX_LEARNER_ROWS)->values() as $index => $attempt) {
            $this->writeScoresheetRow($scoresheet, self::FIRST_LEARNER_ROW + $index, $attempt);
            $this->writeClassRecordRow($classRecord, 8 + $index, $attempt);
        }
    }

    private function writeHeader(Worksheet $sheet, string $assessmentType, ?SchoolClass $class, Learner $fallbackLearner): void
    {
        $school = $fallbackLearner->school;

        $sheet->setCellValue('C3', $assessmentType === 'final_reassessment' ? 'Final Reassessment' : 'Diagnostic Assessment');
        $sheet->setCellValue('C4', $school?->id);
        $sheet->setCellValue('C5', $school?->name);
        $sheet->setCellValue('C6', $class?->teacher?->name ?? '');
        $sheet->setCellValue('C7', $class?->grade_level ?? $fallbackLearner->grade_level ?? 'Grade 1');
        $sheet->setCellValue('C8', $class?->name ?? 'Unassigned');
        $sheet->setCellValue('C9', $fallbackLearner->metadata['language'] ?? 'English');
        $sheet->setCellValue('V1', 'Generated by ReaDirect');
    }

    private function writeClassRecordHeader(Worksheet $sheet, ?SchoolClass $class, Learner $fallbackLearner): void
    {
        $sheet->setCellValue('C4', $fallbackLearner->school?->name);
        $sheet->setCellValue('C5', $class?->teacher?->name ?? '');
        $sheet->setCellValue('C6', $class?->grade_level ?? $fallbackLearner->grade_level ?? 'Grade 1');
    }

    private function writeClassSummaryHeader(Worksheet $sheet, ?SchoolClass $class, Learner $fallbackLearner): void
    {
        $sheet->setCellValue('C4', $fallbackLearner->school?->id);
        $sheet->setCellValue('C5', $fallbackLearner->school?->name);
        $sheet->setCellValue('B8', $class?->name ?? 'Unassigned');
        $sheet->setCellValue('C8', $class?->teacher?->name ?? '');
        $sheet->setCellValue('B9', $class?->name ?? 'Unassigned');
        $sheet->setCellValue('C9', $class?->teacher?->name ?? '');
    }

    private function writeScoresheetRow(Worksheet $sheet, int $row, AssessmentAttempt $attempt): void
    {
        $learner = $attempt->learner;
        $passageEligible = app(CrlaScoringService::class)->shouldAdministerPassage((int) $attempt->task_1_score, (int) $attempt->crla_total_score);
        $passageMetrics = $this->passageMetrics($attempt, $passageEligible);

        $sheet->setCellValue("A{$row}", $row - self::FIRST_LEARNER_ROW + 1);
        $sheet->setCellValueExplicit("B{$row}", $this->lrn($learner), DataType::TYPE_STRING);
        $sheet->setCellValue("C{$row}", $this->learnerName($learner));
        $sheet->setCellValue("D{$row}", $this->sex($learner));
        $sheet->setCellValue("E{$row}", $attempt->completed_at?->format('Y-m-d') ?? $attempt->updated_at?->format('Y-m-d'));
        $sheet->setCellValue("F{$row}", (int) $attempt->task_1_score);
        $sheet->setCellValue("G{$row}", (int) $attempt->task_2a_score);
        $sheet->setCellValue("H{$row}", (int) $attempt->task_2b_score);
        $sheet->setCellValue("I{$row}", (int) $attempt->crla_total_score);
        $sheet->setCellValue("J{$row}", $attempt->crla_classification);
        $sheet->setCellValue("K{$row}", $passageMetrics['story_number']);
        $sheet->setCellValue("L{$row}", $passageMetrics['miscues']);
        $sheet->setCellValue("M{$row}", $passageMetrics['words_read']);
        $sheet->setCellValue("N{$row}", $passageMetrics['minutes']);
        $sheet->setCellValue("O{$row}", $passageMetrics['seconds']);
        $sheet->setCellValue("P{$row}", $passageMetrics['wpm']);
        $sheet->setCellValue("Q{$row}", $passageMetrics['correct_words_fraction']);
        $sheet->setCellValue("R{$row}", (int) ($attempt->comprehension_correct_count ?? 0));
        $sheet->setCellValue("T{$row}", $this->observationLevel($attempt, $passageEligible));
        $sheet->setCellValue("U{$row}", $attempt->reading_classification);
        $sheet->setCellValue("V{$row}", $this->remarks($attempt, $passageEligible));
    }

    private function writeClassRecordRow(Worksheet $sheet, int $row, AssessmentAttempt $attempt): void
    {
        $learner = $attempt->learner;
        $passageEligible = app(CrlaScoringService::class)->shouldAdministerPassage((int) $attempt->task_1_score, (int) $attempt->crla_total_score);
        $passageMetrics = $this->passageMetrics($attempt, $passageEligible);

        $sheet->setCellValue("A{$row}", $row - 7);
        $sheet->setCellValueExplicit("B{$row}", $this->lrn($learner), DataType::TYPE_STRING);
        $sheet->setCellValue("C{$row}", $this->learnerName($learner));
        $sheet->setCellValue("D{$row}", $this->sex($learner));
        $sheet->setCellValue("E{$row}", $attempt->crla_classification);
        $sheet->setCellValue("F{$row}", round(((int) $attempt->crla_total_score / 30) * 100, 2));
        $sheet->setCellValue("G{$row}", (float) ($attempt->reading_accuracy ?? 0));
        $sheet->setCellValue("H{$row}", (float) ($attempt->comprehension_percentage ?? 0));
        $sheet->setCellValue("I{$row}", $passageMetrics['wpm']);
        $sheet->setCellValue("J{$row}", $attempt->reading_classification);
        $sheet->setCellValue("K{$row}", $this->remarks($attempt, $passageEligible));
    }

    private function attemptsForWorkbook(AssessmentAttempt $attempt): Collection
    {
        $attempt->loadMissing('learner');
        $learner = $attempt->learner;

        $query = AssessmentAttempt::query()
            ->with(['learner.school', 'learner.schoolClass'])
            ->where('attempt_type', $attempt->attempt_type)
            ->where('is_sandbox', false)
            ->whereNotNull('crla_total_score')
            ->latest('updated_at')
            ->latest('id');

        if ($learner->class_id) {
            $query->whereHas('learner', fn ($learnerQuery) => $learnerQuery->where('class_id', $learner->class_id));
        } else {
            $query->where('learner_id', $learner->id);
        }

        return $query->get()
            ->unique('learner_id')
            ->sortBy(fn (AssessmentAttempt $row): string => strtolower(trim(($row->learner->last_name ?? '').' '.$row->learner->first_name)))
            ->values();
    }

    private function passageMetrics(AssessmentAttempt $attempt, bool $passageEligible): array
    {
        if (! $passageEligible) {
            return [
                'story_number' => '',
                'miscues' => 0,
                'words_read' => 0,
                'minutes' => '',
                'seconds' => '',
                'wpm' => 0,
                'correct_words_fraction' => 0,
            ];
        }

        $incorrectWords = max(0, (int) ($attempt->incorrect_words ?? 0));
        $wordsRead = max(0, 50 - $incorrectWords);
        $duration = $this->passageDurationSeconds($attempt);
        $wpm = $duration > 0 ? round(($wordsRead / $duration) * 60, 2) : null;

        return [
            'story_number' => 1,
            'miscues' => $incorrectWords,
            'words_read' => $wordsRead,
            'minutes' => $duration > 0 ? intdiv($duration, 60) : '',
            'seconds' => $duration > 0 ? $duration % 60 : '',
            'wpm' => $wpm,
            'correct_words_fraction' => round(((float) ($attempt->reading_accuracy ?? 0)) / 100, 4),
        ];
    }

    private function passageDurationSeconds(AssessmentAttempt $attempt): int
    {
        $audio = AudioFile::query()
            ->where('assessment_attempt_id', $attempt->id)
            ->whereIn('recording_context', ['passage_reading', 'final_passage_reading'])
            ->latest('updated_at')
            ->latest('id')
            ->first();

        $seconds = (int) round((float) ($audio?->duration_seconds ?? (($audio?->duration_ms ?? 0) / 1000)));

        return min(60, max(0, $seconds));
    }

    private function relativeExportPath(string $assessmentType, ?SchoolClass $class, Learner $learner): string
    {
        $owner = $class ? 'class-'.$class->id : 'learner-'.$learner->id;

        return "reports/crla/{$assessmentType}/{$owner}-crla-scoresheet.xlsx";
    }

    private function reportType(string $assessmentType): string
    {
        return $assessmentType === 'final_reassessment'
            ? 'crla_final_reassessment_scoresheet'
            : 'crla_diagnostic_scoresheet';
    }

    private function learnerName(Learner $learner): string
    {
        return trim($learner->first_name.' '.$learner->last_name);
    }

    private function lrn(Learner $learner): string
    {
        return (string) ($learner->metadata['lrn'] ?? $learner->learner_code);
    }

    private function sex(Learner $learner): string
    {
        return (string) ($learner->metadata['sex'] ?? $learner->metadata['gender'] ?? '');
    }

    private function observationLevel(AssessmentAttempt $attempt, bool $passageEligible): string
    {
        if (! $passageEligible) {
            return 'Not Administered';
        }

        return match ($attempt->reading_classification) {
            ReadingComprehensionScoringService::LOW_EMERGING,
            ReadingComprehensionScoringService::HIGH_EMERGING => 'Level 1',
            ReadingComprehensionScoringService::DEVELOPING => 'Level 2',
            ReadingComprehensionScoringService::TRANSITIONING => 'Level 3',
            ReadingComprehensionScoringService::GRADE_LEVEL => 'Level 4',
            default => '',
        };
    }

    private function remarks(AssessmentAttempt $attempt, bool $passageEligible): string
    {
        if ((int) $attempt->task_1_score <= 6) {
            return 'ReaDirect: Task 1A 0-6; Task 2B and passage not administered.';
        }

        if (! $passageEligible) {
            return 'ReaDirect: CRLA total 0-16; passage not administered.';
        }

        return 'Generated by ReaDirect';
    }

    private function raiseMemoryLimit(): void
    {
        $current = ini_get('memory_limit');

        if ($current === false || $current === '-1') {
            return;
        }

        if ($this->memoryLimitBytes($current) < 512 * 1024 * 1024) {
            @ini_set('memory_limit', '512M');
        }
    }

    private function memoryLimitBytes(string $value): int
    {
        $value = trim($value);

        if ($value === '') {
            return 0;
        }

        $unit = strtolower(substr($value, -1));
        $number = (float) $value;

        return match ($unit) {
            'g' => (int) ($number * 1024 * 1024 * 1024),
            'm' => (int) ($number * 1024 * 1024),
            'k' => (int) ($number * 1024),
            default => (int) $number,
        };
    }
}
