<script setup>
import { Link, router } from '@inertiajs/vue3';
import AdminLayout from '../../../Layouts/AdminLayout.vue';
import DashboardCard from '../../../Components/DashboardCard.vue';
import StatusBadge from '../../../Components/StatusBadge.vue';
defineProps({ items: Object, filters: Object, contentTypes: Array });
const filter = (e) => router.get('/admin/assessment-content', Object.fromEntries(new FormData(e.target).entries()), { preserveState: true });
</script>
<template><AdminLayout><div class="mb-5 flex justify-between"><h1 class="text-3xl font-black">Assessment Content</h1><Link href="/admin/assessment-content/create" class="rounded-xl bg-primary px-4 py-2 font-black text-white">Create</Link></div><DashboardCard><form class="grid gap-2 md:grid-cols-3" @submit.prevent="filter"><input name="search" :value="filters.search" class="rounded-xl border p-2" placeholder="Search"><select name="content_type" :value="filters.content_type" class="rounded-xl border p-2"><option value="">All types</option><option v-for="type in contentTypes" :key="type" :value="type">{{ type }}</option></select><button class="rounded-xl bg-primary px-4 font-black text-white">Filter</button></form></DashboardCard><DashboardCard class="mt-4"><table class="w-full text-left text-sm"><thead><tr class="bg-primary-light text-primary"><th class="p-3">Type</th><th class="p-3">Title</th><th class="p-3">Prompt</th><th class="p-3">Status</th><th class="p-3">Action</th></tr></thead><tbody><tr v-for="item in items.data" :key="item.id" class="border-t"><td class="p-3">{{ item.content_type }}</td><td class="p-3 font-bold">{{ item.title }}</td><td class="p-3">{{ item.prompt }}</td><td class="p-3"><StatusBadge :status="item.is_active ? 'Active' : 'Inactive'" /></td><td class="p-3"><Link class="font-black text-primary" :href="`/admin/assessment-content/${item.id}`">View</Link></td></tr></tbody></table></DashboardCard></AdminLayout></template>
