/**
 * useReadingIllustrations.js
 * Maps passage IDs and common words to their illustration images.
 * Frontend-only — no backend changes needed.
 */

// ─── Passage illustrations ────────────────────────────────────────────────────
// Keyed by the passage's source_csv_id (PASS-001, PASS-002, …)
export const passageImages = {
    'PASS-001': '/images/passages/pass-001.png', // Arthur and the Stone
    'PASS-002': '/images/passages/pass-002.png', // Merlin's Listening Lesson
    'PASS-003': '/images/passages/pass-003.png', // The Round Table Promise
    'PASS-004': '/images/passages/pass-004.png', // Robin Hood's Lost Pouch
    'PASS-005': '/images/passages/pass-005.png', // Bea Lights the Harbor
    'PASS-006': '/images/passages/pass-006.png', // Odysseus in the Fog
    'PASS-007': '/images/passages/pass-007.png', // Lila and the Firefly Path
    'PASS-008': '/images/passages/pass-008.png', // The Turtle's Patient Idea
    'PASS-009': '/images/passages/pass-009.png', // The Missing Bookmark
    'PASS-010': '/images/passages/pass-010.png', // The Garden After Heat
};

// ─── Word illustrations (emoji + color card) ──────────────────────────────────
// Covers the common Grade 1 target words used in Task 2B sentences.
// Each entry: { emoji, color (Tailwind bg class), label }
export const wordVisuals = {
    // Animals
    cat:    { emoji: '🐱', color: 'from-orange-200 to-amber-100',  label: 'cat' },
    dog:    { emoji: '🐶', color: 'from-amber-200 to-yellow-100',  label: 'dog' },
    fish:   { emoji: '🐟', color: 'from-blue-200 to-cyan-100',     label: 'fish' },
    bird:   { emoji: '🐦', color: 'from-sky-200 to-blue-100',      label: 'bird' },
    bee:    { emoji: '🐝', color: 'from-yellow-200 to-amber-100',  label: 'bee' },
    duck:   { emoji: '🦆', color: 'from-yellow-200 to-green-100',  label: 'duck' },
    frog:   { emoji: '🐸', color: 'from-green-200 to-emerald-100', label: 'frog' },
    hen:    { emoji: '🐔', color: 'from-red-200 to-orange-100',    label: 'hen' },
    pig:    { emoji: '🐷', color: 'from-pink-200 to-rose-100',     label: 'pig' },
    cow:    { emoji: '🐄', color: 'from-stone-200 to-amber-100',   label: 'cow' },
    ant:    { emoji: '🐜', color: 'from-red-200 to-orange-100',    label: 'ant' },
    bug:    { emoji: '🐛', color: 'from-green-200 to-lime-100',    label: 'bug' },
    fox:    { emoji: '🦊', color: 'from-orange-200 to-amber-100',  label: 'fox' },
    rat:    { emoji: '🐭', color: 'from-gray-200 to-slate-100',    label: 'rat' },
    bat:    { emoji: '🦇', color: 'from-purple-200 to-indigo-100', label: 'bat' },
    crab:   { emoji: '🦀', color: 'from-red-200 to-orange-100',    label: 'crab' },

    // Nature
    sun:    { emoji: '☀️', color: 'from-yellow-200 to-amber-100',  label: 'sun' },
    moon:   { emoji: '🌙', color: 'from-indigo-200 to-blue-100',   label: 'moon' },
    tree:   { emoji: '🌳', color: 'from-green-200 to-emerald-100', label: 'tree' },
    flower: { emoji: '🌸', color: 'from-pink-200 to-rose-100',     label: 'flower' },
    rain:   { emoji: '🌧️', color: 'from-blue-200 to-sky-100',      label: 'rain' },
    star:   { emoji: '⭐', color: 'from-yellow-200 to-amber-100',  label: 'star' },
    cloud:  { emoji: '☁️', color: 'from-slate-200 to-blue-100',    label: 'cloud' },
    wind:   { emoji: '💨', color: 'from-sky-200 to-blue-100',      label: 'wind' },
    snow:   { emoji: '❄️', color: 'from-blue-100 to-sky-50',       label: 'snow' },
    leaf:   { emoji: '🍃', color: 'from-green-200 to-lime-100',    label: 'leaf' },
    rock:   { emoji: '🪨', color: 'from-stone-200 to-gray-100',    label: 'rock' },
    mud:    { emoji: '🟫', color: 'from-amber-300 to-stone-200',   label: 'mud' },
    sand:   { emoji: '🏖️', color: 'from-yellow-200 to-amber-100',  label: 'sand' },
    fire:   { emoji: '🔥', color: 'from-orange-200 to-red-100',    label: 'fire' },
    water:  { emoji: '💧', color: 'from-blue-200 to-cyan-100',     label: 'water' },
    pond:   { emoji: '🌊', color: 'from-blue-200 to-teal-100',     label: 'pond' },
    hill:   { emoji: '⛰️', color: 'from-green-200 to-lime-100',    label: 'hill' },
    path:   { emoji: '🛤️', color: 'from-amber-200 to-yellow-100',  label: 'path' },
    trail:  { emoji: '🌿', color: 'from-green-200 to-emerald-100', label: 'trail' },

    // Objects
    ball:   { emoji: '⚽', color: 'from-slate-200 to-green-100',   label: 'ball' },
    book:   { emoji: '📚', color: 'from-blue-200 to-indigo-100',   label: 'book' },
    bag:    { emoji: '🎒', color: 'from-red-200 to-orange-100',    label: 'bag' },
    hat:    { emoji: '🎩', color: 'from-slate-200 to-gray-100',    label: 'hat' },
    cup:    { emoji: '☕', color: 'from-amber-200 to-yellow-100',  label: 'cup' },
    pen:    { emoji: '✏️', color: 'from-yellow-200 to-amber-100',  label: 'pen' },
    box:    { emoji: '📦', color: 'from-amber-200 to-orange-100',  label: 'box' },
    bed:    { emoji: '🛏️', color: 'from-blue-200 to-indigo-100',   label: 'bed' },
    car:    { emoji: '🚗', color: 'from-red-200 to-orange-100',    label: 'car' },
    bus:    { emoji: '🚌', color: 'from-yellow-200 to-amber-100',  label: 'bus' },
    ship:   { emoji: '🚢', color: 'from-blue-200 to-cyan-100',     label: 'ship' },
    boat:   { emoji: '⛵', color: 'from-sky-200 to-blue-100',      label: 'boat' },
    kite:   { emoji: '🪁', color: 'from-pink-200 to-purple-100',   label: 'kite' },
    lamp:   { emoji: '💡', color: 'from-yellow-200 to-amber-100',  label: 'lamp' },
    drum:   { emoji: '🥁', color: 'from-orange-200 to-amber-100',  label: 'drum' },
    flag:   { emoji: '🚩', color: 'from-red-200 to-orange-100',    label: 'flag' },
    key:    { emoji: '🔑', color: 'from-yellow-200 to-amber-100',  label: 'key' },
    map:    { emoji: '🗺️', color: 'from-amber-200 to-yellow-100',  label: 'map' },
    net:    { emoji: '🕸️', color: 'from-slate-200 to-gray-100',    label: 'net' },
    pot:    { emoji: '🫕', color: 'from-gray-200 to-stone-100',    label: 'pot' },
    rope:   { emoji: '🪢', color: 'from-amber-300 to-yellow-100',  label: 'rope' },
    tent:   { emoji: '⛺', color: 'from-green-200 to-lime-100',    label: 'tent' },
    wheel:  { emoji: '🔵', color: 'from-slate-200 to-blue-100',    label: 'wheel' },
    bell:   { emoji: '🔔', color: 'from-yellow-200 to-amber-100',  label: 'bell' },

    // Food
    egg:    { emoji: '🥚', color: 'from-yellow-100 to-amber-50',   label: 'egg' },
    bread:  { emoji: '🍞', color: 'from-amber-200 to-yellow-100',  label: 'bread' },
    rice:   { emoji: '🍚', color: 'from-yellow-100 to-white',      label: 'rice' },
    milk:   { emoji: '🥛', color: 'from-blue-100 to-white',        label: 'milk' },
    cake:   { emoji: '🎂', color: 'from-pink-200 to-rose-100',     label: 'cake' },
    soup:   { emoji: '🍜', color: 'from-amber-200 to-orange-100',  label: 'soup' },
    fish2:  { emoji: '🐟', color: 'from-blue-200 to-cyan-100',     label: 'fish' },

    // People / actions
    hand:   { emoji: '🤚', color: 'from-amber-200 to-orange-100',  label: 'hand' },
    run:    { emoji: '🏃', color: 'from-green-200 to-lime-100',    label: 'run' },
    jump:   { emoji: '🤸', color: 'from-sky-200 to-blue-100',      label: 'jump' },
    sit:    { emoji: '🧘', color: 'from-purple-200 to-violet-100', label: 'sit' },
    smile:  { emoji: '😊', color: 'from-yellow-200 to-amber-100',  label: 'smile' },
    cry:    { emoji: '😢', color: 'from-blue-200 to-sky-100',      label: 'cry' },
    play:   { emoji: '🎮', color: 'from-purple-200 to-blue-100',   label: 'play' },
    swim:   { emoji: '🏊', color: 'from-blue-200 to-cyan-100',     label: 'swim' },
    sing:   { emoji: '🎵', color: 'from-pink-200 to-rose-100',     label: 'sing' },
    eat:    { emoji: '🍽️', color: 'from-amber-200 to-yellow-100',  label: 'eat' },
    sleep:  { emoji: '😴', color: 'from-indigo-200 to-blue-100',   label: 'sleep' },
    read:   { emoji: '📖', color: 'from-blue-200 to-indigo-100',   label: 'read' },
    kick:   { emoji: '⚽', color: 'from-green-200 to-lime-100',    label: 'kick' },
    help:   { emoji: '🤝', color: 'from-green-200 to-emerald-100', label: 'help' },
    wash:   { emoji: '🧼', color: 'from-blue-200 to-cyan-100',     label: 'wash' },
    pull:   { emoji: '💪', color: 'from-orange-200 to-amber-100',  label: 'pull' },
    push:   { emoji: '🤜', color: 'from-slate-200 to-gray-100',    label: 'push' },
    lift:   { emoji: '🏋️', color: 'from-purple-200 to-violet-100', label: 'lift' },
    wave:   { emoji: '👋', color: 'from-yellow-200 to-amber-100',  label: 'wave' },
    give:   { emoji: '🎁', color: 'from-red-200 to-pink-100',      label: 'give' },
    show:   { emoji: '👀', color: 'from-blue-200 to-sky-100',      label: 'show' },

    // Colors
    red:    { emoji: '🔴', color: 'from-red-300 to-rose-100',      label: 'red' },
    blue:   { emoji: '🔵', color: 'from-blue-300 to-sky-100',      label: 'blue' },
    green:  { emoji: '🟢', color: 'from-green-300 to-lime-100',    label: 'green' },
    yellow: { emoji: '🟡', color: 'from-yellow-300 to-amber-100',  label: 'yellow' },
    black:  { emoji: '⚫', color: 'from-gray-400 to-slate-200',    label: 'black' },
    white:  { emoji: '⚪', color: 'from-gray-100 to-white',        label: 'white' },
    pink:   { emoji: '🩷', color: 'from-pink-200 to-rose-100',     label: 'pink' },
    gray:   { emoji: '🩶', color: 'from-gray-300 to-slate-100',    label: 'gray' },

    // Descriptors / adjectives
    big:    { emoji: '🔆', color: 'from-orange-200 to-amber-100',  label: 'big' },
    small:  { emoji: '🔅', color: 'from-slate-200 to-blue-100',    label: 'small' },
    hot:    { emoji: '🌡️', color: 'from-red-200 to-orange-100',    label: 'hot' },
    cold:   { emoji: '🧊', color: 'from-blue-200 to-cyan-100',     label: 'cold' },
    soft:   { emoji: '🧸', color: 'from-amber-100 to-yellow-50',   label: 'soft' },
    hard:   { emoji: '🪨', color: 'from-stone-200 to-gray-100',    label: 'hard' },
    bright: { emoji: '✨', color: 'from-yellow-200 to-amber-100',  label: 'bright' },
    dark:   { emoji: '🌑', color: 'from-slate-400 to-gray-200',    label: 'dark' },
    dry:    { emoji: '🌵', color: 'from-amber-200 to-yellow-100',  label: 'dry' },
    wet:    { emoji: '💦', color: 'from-blue-200 to-cyan-100',     label: 'wet' },

    // Places
    home:   { emoji: '🏠', color: 'from-amber-200 to-yellow-100',  label: 'home' },
    school: { emoji: '🏫', color: 'from-blue-200 to-sky-100',      label: 'school' },
    park:   { emoji: '🌳', color: 'from-green-200 to-lime-100',    label: 'park' },
    farm:   { emoji: '🌾', color: 'from-yellow-200 to-amber-100',  label: 'farm' },
    store:  { emoji: '🏪', color: 'from-orange-200 to-amber-100',  label: 'store' },
    garden: { emoji: '🌻', color: 'from-green-200 to-lime-100',    label: 'garden' },
    class:  { emoji: '🏫', color: 'from-blue-200 to-indigo-100',   label: 'class' },

    // Expanded Module 2 Words
    back    : { emoji: '🔙', color: 'from-slate-200 to-slate-100', label: 'back' },
    bad     : { emoji: '👎', color: 'from-slate-200 to-slate-100', label: 'bad' },
    bake    : { emoji: '🧁', color: 'from-slate-200 to-slate-100', label: 'bake' },
    bark    : { emoji: '🐕', color: 'from-slate-200 to-slate-100', label: 'bark' },
    bin     : { emoji: '🗑️', color: 'from-slate-200 to-slate-100', label: 'bin' },
    block   : { emoji: '🧱', color: 'from-slate-200 to-slate-100', label: 'block' },
    blush   : { emoji: '😳', color: 'from-slate-200 to-slate-100', label: 'blush' },
    brag    : { emoji: '🗣️', color: 'from-slate-200 to-slate-100', label: 'brag' },
    brain   : { emoji: '🧠', color: 'from-slate-200 to-slate-100', label: 'brain' },
    brush   : { emoji: '🖌️', color: 'from-slate-200 to-slate-100', label: 'brush' },
    bun     : { emoji: '🍔', color: 'from-slate-200 to-slate-100', label: 'bun' },
    cage    : { emoji: '🪤', color: 'from-slate-200 to-slate-100', label: 'cage' },
    call    : { emoji: '📞', color: 'from-slate-200 to-slate-100', label: 'call' },
    can     : { emoji: '🥫', color: 'from-slate-200 to-slate-100', label: 'can' },
    cap     : { emoji: '🧢', color: 'from-slate-200 to-slate-100', label: 'cap' },
    card    : { emoji: '🃏', color: 'from-slate-200 to-slate-100', label: 'card' },
    cash    : { emoji: '💵', color: 'from-slate-200 to-slate-100', label: 'cash' },
    chain   : { emoji: '⛓️', color: 'from-slate-200 to-slate-100', label: 'chain' },
    chair   : { emoji: '🪑', color: 'from-slate-200 to-slate-100', label: 'chair' },
    chin    : { emoji: '👤', color: 'from-slate-200 to-slate-100', label: 'chin' },
    chip    : { emoji: '🍟', color: 'from-slate-200 to-slate-100', label: 'chip' },
    clad    : { emoji: '👕', color: 'from-slate-200 to-slate-100', label: 'clad' },
    clam    : { emoji: '🦪', color: 'from-slate-200 to-slate-100', label: 'clam' },
    clap    : { emoji: '👏', color: 'from-slate-200 to-slate-100', label: 'clap' },
    clip    : { emoji: '📎', color: 'from-slate-200 to-slate-100', label: 'clip' },
    clock   : { emoji: '⏰', color: 'from-slate-200 to-slate-100', label: 'clock' },
    clog    : { emoji: '👞', color: 'from-slate-200 to-slate-100', label: 'clog' },
    club    : { emoji: '⛳', color: 'from-slate-200 to-slate-100', label: 'club' },
    coat    : { emoji: '🧥', color: 'from-slate-200 to-slate-100', label: 'coat' },
    cop     : { emoji: '👮', color: 'from-slate-200 to-slate-100', label: 'cop' },
    corn    : { emoji: '🌽', color: 'from-slate-200 to-slate-100', label: 'corn' },
    cot     : { emoji: '🛏️', color: 'from-slate-200 to-slate-100', label: 'cot' },
    crash   : { emoji: '💥', color: 'from-slate-200 to-slate-100', label: 'crash' },
    cub     : { emoji: '🐻', color: 'from-slate-200 to-slate-100', label: 'cub' },
    dad     : { emoji: '👨', color: 'from-slate-200 to-slate-100', label: 'dad' },
    dam     : { emoji: '🦫', color: 'from-slate-200 to-slate-100', label: 'dam' },
    dash    : { emoji: '💨', color: 'from-slate-200 to-slate-100', label: 'dash' },
    date    : { emoji: '📅', color: 'from-slate-200 to-slate-100', label: 'date' },
    den     : { emoji: '🐻', color: 'from-slate-200 to-slate-100', label: 'den' },
    dig     : { emoji: '⛏️', color: 'from-slate-200 to-slate-100', label: 'dig' },
    dip     : { emoji: '🥣', color: 'from-slate-200 to-slate-100', label: 'dip' },
    dish    : { emoji: '🍽️', color: 'from-slate-200 to-slate-100', label: 'dish' },
    dock    : { emoji: '⛵', color: 'from-slate-200 to-slate-100', label: 'dock' },
    dot     : { emoji: '🔴', color: 'from-slate-200 to-slate-100', label: 'dot' },
    drag    : { emoji: '🏗️', color: 'from-slate-200 to-slate-100', label: 'drag' },
    drill   : { emoji: '🛠️', color: 'from-slate-200 to-slate-100', label: 'drill' },
    drip    : { emoji: '💧', color: 'from-slate-200 to-slate-100', label: 'drip' },
    drop    : { emoji: '💧', color: 'from-slate-200 to-slate-100', label: 'drop' },
    dwell   : { emoji: '🏠', color: 'from-slate-200 to-slate-100', label: 'dwell' },
    fall    : { emoji: '🍂', color: 'from-slate-200 to-slate-100', label: 'fall' },
    fan     : { emoji: '🪭', color: 'from-slate-200 to-slate-100', label: 'fan' },
    fed     : { emoji: '🥣', color: 'from-slate-200 to-slate-100', label: 'fed' },
    fell    : { emoji: '📉', color: 'from-slate-200 to-slate-100', label: 'fell' },
    fig     : { emoji: '🍐', color: 'from-slate-200 to-slate-100', label: 'fig' },
    fill    : { emoji: '🥛', color: 'from-slate-200 to-slate-100', label: 'fill' },
    fin     : { emoji: '🦈', color: 'from-slate-200 to-slate-100', label: 'fin' },
    finish  : { emoji: '🏁', color: 'from-slate-200 to-slate-100', label: 'finish' },
    fist    : { emoji: '✊', color: 'from-slate-200 to-slate-100', label: 'fist' },
    fit     : { emoji: '👕', color: 'from-slate-200 to-slate-100', label: 'fit' },
    flake   : { emoji: '❄️', color: 'from-slate-200 to-slate-100', label: 'flake' },
    flash   : { emoji: '📸', color: 'from-slate-200 to-slate-100', label: 'flash' },
    flat    : { emoji: '➖', color: 'from-slate-200 to-slate-100', label: 'flat' },
    flip    : { emoji: '🙃', color: 'from-slate-200 to-slate-100', label: 'flip' },
    flock   : { emoji: '🐦', color: 'from-slate-200 to-slate-100', label: 'flock' },
    flog    : { emoji: '💥', color: 'from-slate-200 to-slate-100', label: 'flog' },
    fog     : { emoji: '🌫️', color: 'from-slate-200 to-slate-100', label: 'fog' },
    fun     : { emoji: '🎉', color: 'from-slate-200 to-slate-100', label: 'fun' },
    gap     : { emoji: '↔️', color: 'from-slate-200 to-slate-100', label: 'gap' },
    gate    : { emoji: '⛩️', color: 'from-slate-200 to-slate-100', label: 'gate' },
    get     : { emoji: '🤲', color: 'from-slate-200 to-slate-100', label: 'get' },
    glad    : { emoji: '😄', color: 'from-slate-200 to-slate-100', label: 'glad' },
    got     : { emoji: '👍', color: 'from-slate-200 to-slate-100', label: 'got' },
    grain   : { emoji: '🌾', color: 'from-slate-200 to-slate-100', label: 'grain' },
    gram    : { emoji: '⚖️', color: 'from-slate-200 to-slate-100', label: 'gram' },
    grub    : { emoji: '🐛', color: 'from-slate-200 to-slate-100', label: 'grub' },
    had     : { emoji: '👍', color: 'from-slate-200 to-slate-100', label: 'had' },
    hall    : { emoji: '🏫', color: 'from-slate-200 to-slate-100', label: 'hall' },
    ham     : { emoji: '🍖', color: 'from-slate-200 to-slate-100', label: 'ham' },
    hip     : { emoji: '🦴', color: 'from-slate-200 to-slate-100', label: 'hip' },
    hit     : { emoji: '🥊', color: 'from-slate-200 to-slate-100', label: 'hit' },
    hog     : { emoji: '🐖', color: 'from-slate-200 to-slate-100', label: 'hog' },
    hop     : { emoji: '🐇', color: 'from-slate-200 to-slate-100', label: 'hop' },
    hug     : { emoji: '🤗', color: 'from-slate-200 to-slate-100', label: 'hug' },
    jack    : { emoji: '🃏', color: 'from-slate-200 to-slate-100', label: 'jack' },
    jam     : { emoji: '🍓', color: 'from-slate-200 to-slate-100', label: 'jam' },
    jet     : { emoji: '✈️', color: 'from-slate-200 to-slate-100', label: 'jet' },
    jig     : { emoji: '🕺', color: 'from-slate-200 to-slate-100', label: 'jig' },
    jog     : { emoji: '🏃', color: 'from-slate-200 to-slate-100', label: 'jog' },
    jug     : { emoji: '🏺', color: 'from-slate-200 to-slate-100', label: 'jug' },
    kit     : { emoji: '🧰', color: 'from-slate-200 to-slate-100', label: 'kit' },
    knit    : { emoji: '🧶', color: 'from-slate-200 to-slate-100', label: 'knit' },
    lake    : { emoji: '🏞️', color: 'from-slate-200 to-slate-100', label: 'lake' },
    lap     : { emoji: '🦵', color: 'from-slate-200 to-slate-100', label: 'lap' },
    led     : { emoji: '🚶', color: 'from-slate-200 to-slate-100', label: 'led' },
    leg     : { emoji: '🦵', color: 'from-slate-200 to-slate-100', label: 'leg' },
    let     : { emoji: '👍', color: 'from-slate-200 to-slate-100', label: 'let' },
    lip     : { emoji: '👄', color: 'from-slate-200 to-slate-100', label: 'lip' },
    loaf    : { emoji: '🍞', color: 'from-slate-200 to-slate-100', label: 'loaf' },
    lock    : { emoji: '🔒', color: 'from-slate-200 to-slate-100', label: 'lock' },
    log     : { emoji: '🪵', color: 'from-slate-200 to-slate-100', label: 'log' },
    mad     : { emoji: '😠', color: 'from-slate-200 to-slate-100', label: 'mad' },
    mail    : { emoji: '✉️', color: 'from-slate-200 to-slate-100', label: 'mail' },
    make    : { emoji: '🛠️', color: 'from-slate-200 to-slate-100', label: 'make' },
    man     : { emoji: '👨', color: 'from-slate-200 to-slate-100', label: 'man' },
    mash    : { emoji: '🥔', color: 'from-slate-200 to-slate-100', label: 'mash' },
    mat     : { emoji: '🔲', color: 'from-slate-200 to-slate-100', label: 'mat' },
    men     : { emoji: '👨‍👨‍👦', color: 'from-slate-200 to-slate-100', label: 'men' },
    met     : { emoji: '🤝', color: 'from-slate-200 to-slate-100', label: 'met' },
    mice    : { emoji: '🐁', color: 'from-slate-200 to-slate-100', label: 'mice' },
    mill    : { emoji: '🏭', color: 'from-slate-200 to-slate-100', label: 'mill' },
    mop     : { emoji: '🧹', color: 'from-slate-200 to-slate-100', label: 'mop' },
    mug     : { emoji: '🍺', color: 'from-slate-200 to-slate-100', label: 'mug' },
    nail    : { emoji: '🔨', color: 'from-slate-200 to-slate-100', label: 'nail' },
    nap     : { emoji: '😴', color: 'from-slate-200 to-slate-100', label: 'nap' },
    nice    : { emoji: '😊', color: 'from-slate-200 to-slate-100', label: 'nice' },
    nun     : { emoji: '⛪', color: 'from-slate-200 to-slate-100', label: 'nun' },
    pack    : { emoji: '🎒', color: 'from-slate-200 to-slate-100', label: 'pack' },
    pad     : { emoji: '📝', color: 'from-slate-200 to-slate-100', label: 'pad' },
    pail    : { emoji: '🪣', color: 'from-slate-200 to-slate-100', label: 'pail' },
    pain    : { emoji: '🤕', color: 'from-slate-200 to-slate-100', label: 'pain' },
    pan     : { emoji: '🍳', color: 'from-slate-200 to-slate-100', label: 'pan' },
    pat     : { emoji: '✋', color: 'from-slate-200 to-slate-100', label: 'pat' },
    pet     : { emoji: '🐕', color: 'from-slate-200 to-slate-100', label: 'pet' },
    pin     : { emoji: '📌', color: 'from-slate-200 to-slate-100', label: 'pin' },
    pinkish : { emoji: '🩷', color: 'from-slate-200 to-slate-100', label: 'pinkish' },
    pit     : { emoji: '🕳️', color: 'from-slate-200 to-slate-100', label: 'pit' },
    plain   : { emoji: '🌾', color: 'from-slate-200 to-slate-100', label: 'plain' },
    plan    : { emoji: '📋', color: 'from-slate-200 to-slate-100', label: 'plan' },
    plot    : { emoji: '🗺️', color: 'from-slate-200 to-slate-100', label: 'plot' },
    plug    : { emoji: '🔌', color: 'from-slate-200 to-slate-100', label: 'plug' },
    pop     : { emoji: '🎈', color: 'from-slate-200 to-slate-100', label: 'pop' },
    price   : { emoji: '💲', color: 'from-slate-200 to-slate-100', label: 'price' },
    pun     : { emoji: '😆', color: 'from-slate-200 to-slate-100', label: 'pun' },
    race    : { emoji: '🏁', color: 'from-slate-200 to-slate-100', label: 'race' },
    rack    : { emoji: '🧥', color: 'from-slate-200 to-slate-100', label: 'rack' },
    rag     : { emoji: '🧻', color: 'from-slate-200 to-slate-100', label: 'rag' },
    rail    : { emoji: '🛤️', color: 'from-slate-200 to-slate-100', label: 'rail' },
    rake    : { emoji: '🧹', color: 'from-slate-200 to-slate-100', label: 'rake' },
    ram     : { emoji: '🐏', color: 'from-slate-200 to-slate-100', label: 'ram' },
    ran     : { emoji: '🏃', color: 'from-slate-200 to-slate-100', label: 'ran' },
    rash    : { emoji: '🔴', color: 'from-slate-200 to-slate-100', label: 'rash' },
    relish  : { emoji: '🥒', color: 'from-slate-200 to-slate-100', label: 'relish' },
    rid     : { emoji: '🗑️', color: 'from-slate-200 to-slate-100', label: 'rid' },
    rig     : { emoji: '🏗️', color: 'from-slate-200 to-slate-100', label: 'rig' },
    rip     : { emoji: '📄', color: 'from-slate-200 to-slate-100', label: 'rip' },
    rub     : { emoji: '👐', color: 'from-slate-200 to-slate-100', label: 'rub' },
    rug     : { emoji: '🔲', color: 'from-slate-200 to-slate-100', label: 'rug' },
    sack    : { emoji: '🛍️', color: 'from-slate-200 to-slate-100', label: 'sack' },
    sad     : { emoji: '😢', color: 'from-slate-200 to-slate-100', label: 'sad' },
    said    : { emoji: '💬', color: 'from-slate-200 to-slate-100', label: 'said' },
    sail    : { emoji: '⛵', color: 'from-slate-200 to-slate-100', label: 'sail' },
    sat     : { emoji: '🪑', color: 'from-slate-200 to-slate-100', label: 'sat' },
    scrub   : { emoji: '🧽', color: 'from-slate-200 to-slate-100', label: 'scrub' },
    seed    : { emoji: '🌱', color: 'from-slate-200 to-slate-100', label: 'seed' },
    set     : { emoji: '🍽️', color: 'from-slate-200 to-slate-100', label: 'set' },
    shake   : { emoji: '🤝', color: 'from-slate-200 to-slate-100', label: 'shake' },
    share   : { emoji: '🤲', color: 'from-slate-200 to-slate-100', label: 'share' },
    shed    : { emoji: '🛖', color: 'from-slate-200 to-slate-100', label: 'shed' },
    shell   : { emoji: '🐚', color: 'from-slate-200 to-slate-100', label: 'shell' },
    shock   : { emoji: '😲', color: 'from-slate-200 to-slate-100', label: 'shock' },
    shop    : { emoji: '🏪', color: 'from-slate-200 to-slate-100', label: 'shop' },
    sip     : { emoji: '🥤', color: 'from-slate-200 to-slate-100', label: 'sip' },
    slam    : { emoji: '💥', color: 'from-slate-200 to-slate-100', label: 'slam' },
    sled    : { emoji: '🛷', color: 'from-slate-200 to-slate-100', label: 'sled' },
    slice   : { emoji: '🍕', color: 'from-slate-200 to-slate-100', label: 'slice' },
    slip    : { emoji: '🍌', color: 'from-slate-200 to-slate-100', label: 'slip' },
    slot    : { emoji: '🎰', color: 'from-slate-200 to-slate-100', label: 'slot' },
    slug    : { emoji: '🐌', color: 'from-slate-200 to-slate-100', label: 'slug' },
    smell   : { emoji: '👃', color: 'from-slate-200 to-slate-100', label: 'smell' },
    smog    : { emoji: '🌫️', color: 'from-slate-200 to-slate-100', label: 'smog' },
    snag    : { emoji: '🧶', color: 'from-slate-200 to-slate-100', label: 'snag' },
    snail   : { emoji: '🐌', color: 'from-slate-200 to-slate-100', label: 'snail' },
    snake   : { emoji: '🐍', color: 'from-slate-200 to-slate-100', label: 'snake' },
    snap    : { emoji: '🤌', color: 'from-slate-200 to-slate-100', label: 'snap' },
    snug    : { emoji: '🛌', color: 'from-slate-200 to-slate-100', label: 'snug' },
    sock    : { emoji: '🧦', color: 'from-slate-200 to-slate-100', label: 'sock' },
    son     : { emoji: '👦', color: 'from-slate-200 to-slate-100', label: 'son' },
    sped    : { emoji: '🏎️', color: 'from-slate-200 to-slate-100', label: 'sped' },
    spell   : { emoji: '🪄', color: 'from-slate-200 to-slate-100', label: 'spell' },
    spice   : { emoji: '🌶️', color: 'from-slate-200 to-slate-100', label: 'spice' },
    spill   : { emoji: '💦', color: 'from-slate-200 to-slate-100', label: 'spill' },
    spin    : { emoji: '🌀', color: 'from-slate-200 to-slate-100', label: 'spin' },
    splash  : { emoji: '💦', color: 'from-slate-200 to-slate-100', label: 'splash' },
    split   : { emoji: '➗', color: 'from-slate-200 to-slate-100', label: 'split' },
    spot    : { emoji: '🎯', color: 'from-slate-200 to-slate-100', label: 'spot' },
    spun    : { emoji: '🌀', color: 'from-slate-200 to-slate-100', label: 'spun' },
    stack   : { emoji: '🥞', color: 'from-slate-200 to-slate-100', label: 'stack' },
    stain   : { emoji: '👕', color: 'from-slate-200 to-slate-100', label: 'stain' },
    stall   : { emoji: '🐎', color: 'from-slate-200 to-slate-100', label: 'stall' },
    still   : { emoji: '🤫', color: 'from-slate-200 to-slate-100', label: 'still' },
    stop    : { emoji: '🛑', color: 'from-slate-200 to-slate-100', label: 'stop' },
    stub    : { emoji: '🦶', color: 'from-slate-200 to-slate-100', label: 'stub' },
    stun    : { emoji: '😵', color: 'from-slate-200 to-slate-100', label: 'stun' },
    sub     : { emoji: '🥪', color: 'from-slate-200 to-slate-100', label: 'sub' },
    swish   : { emoji: '💨', color: 'from-slate-200 to-slate-100', label: 'swish' },
    tag     : { emoji: '🏷️', color: 'from-slate-200 to-slate-100', label: 'tag' },
    tail    : { emoji: '🐕', color: 'from-slate-200 to-slate-100', label: 'tail' },
    tall    : { emoji: '🦒', color: 'from-slate-200 to-slate-100', label: 'tall' },
    tan     : { emoji: '🟤', color: 'from-slate-200 to-slate-100', label: 'tan' },
    tap     : { emoji: '🚰', color: 'from-slate-200 to-slate-100', label: 'tap' },
    tell    : { emoji: '🗣️', color: 'from-slate-200 to-slate-100', label: 'tell' },
    ten     : { emoji: '🔟', color: 'from-slate-200 to-slate-100', label: 'ten' },
    then    : { emoji: '⏳', color: 'from-slate-200 to-slate-100', label: 'then' },
    thin    : { emoji: '📏', color: 'from-slate-200 to-slate-100', label: 'thin' },
    tin     : { emoji: '🥫', color: 'from-slate-200 to-slate-100', label: 'tin' },
    tip     : { emoji: '💰', color: 'from-slate-200 to-slate-100', label: 'tip' },
    top     : { emoji: '🔝', color: 'from-slate-200 to-slate-100', label: 'top' },
    track   : { emoji: '🛤️', color: 'from-slate-200 to-slate-100', label: 'track' },
    train   : { emoji: '🚂', color: 'from-slate-200 to-slate-100', label: 'train' },
    trash   : { emoji: '🗑️', color: 'from-slate-200 to-slate-100', label: 'trash' },
    tray    : { emoji: '🍱', color: 'from-slate-200 to-slate-100', label: 'tray' },
    tub     : { emoji: '🛁', color: 'from-slate-200 to-slate-100', label: 'tub' },
    twice   : { emoji: '✌️', color: 'from-slate-200 to-slate-100', label: 'twice' },
    twig    : { emoji: '🌿', color: 'from-slate-200 to-slate-100', label: 'twig' },
    van     : { emoji: '🚐', color: 'from-slate-200 to-slate-100', label: 'van' },
    wag     : { emoji: '🐕', color: 'from-slate-200 to-slate-100', label: 'wag' },
    wall    : { emoji: '🧱', color: 'from-slate-200 to-slate-100', label: 'wall' },
    wed     : { emoji: '💍', color: 'from-slate-200 to-slate-100', label: 'wed' },
    well    : { emoji: '🚰', color: 'from-slate-200 to-slate-100', label: 'well' },
    when    : { emoji: '⏰', color: 'from-slate-200 to-slate-100', label: 'when' },
    wig     : { emoji: '💇', color: 'from-slate-200 to-slate-100', label: 'wig' },
    will    : { emoji: '📜', color: 'from-slate-200 to-slate-100', label: 'will' },
    win     : { emoji: '🏆', color: 'from-slate-200 to-slate-100', label: 'win' },
    wish    : { emoji: '🌠', color: 'from-slate-200 to-slate-100', label: 'wish' },
    wit     : { emoji: '🧠', color: 'from-slate-200 to-slate-100', label: 'wit' },
    wren    : { emoji: '🐦', color: 'from-slate-200 to-slate-100', label: 'wren' },
    yam     : { emoji: '🍠', color: 'from-slate-200 to-slate-100', label: 'yam' },
};

/**
 * Returns the illustration URL for a reading passage.
 * @param {Object} passage - The passage object with payload.source_csv_id or id
 * @returns {string|null}
 */
export function getPassageImage(passage) {
    if (!passage) return null;
    const csvId = passage?.payload?.source_csv_id ?? passage?.source_csv_id ?? null;
    if (csvId && passageImages[csvId]) return passageImages[csvId];
    // Fallback: try matching by passage id
    const id = passage?.id ?? '';
    for (const [key, url] of Object.entries(passageImages)) {
        if (String(id).includes(key.replace('PASS-', ''))) return url;
    }
    return null;
}

/**
 * Returns the visual data for a word (emoji + gradient color).
 * @param {string} word - The target word
 * @returns {{ emoji: string, color: string, label: string }|null}
 */
export function getWordVisual(word) {
    if (!word) return null;
    const key = word.toLowerCase().trim();
    return wordVisuals[key] ?? null;
}
