<script setup>
import { useForm } from '@inertiajs/vue3';
import AdminLayout from '../../../Layouts/AdminLayout.vue';
import DashboardCard from '../../../Components/DashboardCard.vue';
const props = defineProps({ learner: Object, schools: Array, classes: Array, modules: Array });
const form = useForm({ school_id: props.learner?.school_id ?? '', class_id: props.learner?.class_id ?? '', current_module_id: props.learner?.current_module_id ?? '', learner_code: props.learner?.learner_code ?? '', first_name: props.learner?.first_name ?? '', last_name: props.learner?.last_name ?? '', grade_level: props.learner?.grade_level ?? 'Grade 1', current_stage: props.learner?.current_stage ?? '' });
const submit = () => props.learner ? form.put(`/admin/learners/${props.learner.public_id}`) : form.post('/admin/learners');
</script>
<template><AdminLayout><h1 class="mb-5 text-3xl font-black">{{ learner ? 'Edit Learner' : 'Create Learner' }}</h1><DashboardCard><form class="grid gap-4 md:grid-cols-2" @submit.prevent="submit"><input v-model="form.learner_code" class="rounded-xl border p-3" placeholder="Learner code"><input v-model="form.first_name" class="rounded-xl border p-3" placeholder="First name"><input v-model="form.last_name" class="rounded-xl border p-3" placeholder="Last name"><input v-model="form.grade_level" class="rounded-xl border p-3" placeholder="Grade level"><select v-model="form.school_id" class="rounded-xl border p-3"><option value="">School</option><option v-for="school in schools" :key="school.id" :value="school.id">{{ school.name }}</option></select><select v-model="form.class_id" class="rounded-xl border p-3"><option value="">Class</option><option v-for="item in classes" :key="item.id" :value="item.id">{{ item.school?.name }} - {{ item.name }}</option></select><select v-model="form.current_module_id" class="rounded-xl border p-3"><option value="">No module</option><option v-for="module in modules" :key="module.id" :value="module.id">{{ module.title }}</option></select><input v-model="form.current_stage" class="rounded-xl border p-3" placeholder="Current stage"><button class="rounded-xl bg-primary px-4 py-3 font-black text-white md:col-span-2">Save</button></form></DashboardCard></AdminLayout></template>
